spring.application.name=toy

spring.datasource.url=${DATABASE_DEV_URL}
spring.datasource.username=${DATABASE_DEV_USER_NAME}
spring.datasource.password=${DATABASE_DEV_PASSWORD}
spring.datasource.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
server.port=8080
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.servlet.multipart.max-file-size=110MB
spring.servlet.multipart.max-request-size=110MB

#limpando cache
